#!/bin/bash

file="$HOME/.local/share/bmarks"

activate_window() {
    window_id=$(xdotool search --onlyvisible --class "Firefox")
    count=$(printf "$window_id" | cat -n - | awk 'END{print}' | awk -F ' ' '{print $1}')
    [ $count -gt 1 ] && xdotool key --clearmodifiers alt+1 || xdotool windowactivate $window_id
    case $1 in
	copy) 
	    xdotool key --clearmodifiers ctrl+l ctrl+c Escape ;;
	insert)
	    xdotool key --clearmodifiers ctrl+l
	    setxkbmap; xdotool type --delay 20 "$selected_url"
	    xdotool key --clearmodifiers Return
	    ;;
    esac
}

create_bookmark() {
    activate_window copy
    name=$(printf "" | dmenu -p "Bookmark Name" -sf "#b8bb26")
    url=$(xclip -o -selection clipboard | cut -d'/' -f 1-3)

    [ -z "$name" ] && notify-send "Error: Name can't be empty" || { 
    [[ $url =~ ^(http|https)://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}[a-zA-Z0-9.-/]*$ ]] ||
    { notify-send "Error: Wrong URL format"; exit 1 ;}

    [[ $url =~ /$ ]] || url="$url/"

    grep -q "$url" "$file" && notify-send "Error: URL already exists" || {
        grep -q "^$name" "$file" && {
            id=2
	    while grep -q "^${name} (${id})" "$file"; do
                id=$((id + 1))
            done
	    name="${name} (${id})" ;} || { name="${name} (1)" ;}
    echo "$name | $url" >> "$file"
    notify-send "$name added successfully" "$url"
    sort -t '|' -k1,1 -o "$file" "$file"
    xsel -bc; xsel -c ;} ;}
}

insert_bookmark() {
    [ -s "$file" ] || { notify-send "Error: No bookmarks found"; exit 1 ;} &&
    selected_name=$(awk -F '|' '{print $1}' $file | awk '{$1=$1};1' |\
    dmenu -i -p "Select Bookmark" -sf "#83a598")
    [ -z "$selected_name" ] && { notify-send "Error: No bookmark selected"; exit 1 ;} ||
    selected_url=$(grep -w "^$selected_name |"  "$file" | awk -F '|' '{print $2}' |\
    awk '{$1=$1};1')
    activate_window insert
    xsel -bc; xsel -c
}

replace_bookmark() {
    activate_window copy
    [ -s "$file" ] || { notify-send "Error: No bookmarks found"; exit 1 ;} &&
    selected_name=$(cat $file | awk -F '|' '{print $1}' | awk '{$1=$1};1' |\
    dmenu -i -p "Replace Bookmark" -sf "#F9BC2E")
    [ -z "$selected_name" ] && { notify-send "Error: No bookmark selected"; exit 1 ;} ||
    selected_url=$(grep -w "^$selected_name"  "$file" | awk -F '|' '{print $2}' |\
    awk '{$1=$1};1')
    query=$(xclip -o selection clipboard | cut -d "/" -f4-)
    xdotool type "$selected_url$query" && xdotool key Return
    xsel -bc; xsel -c
}

edit_bookmark() {
    [ -s "$file" ] || { notify-send "Error: No bookmarks found"; exit 1 ;} &&
    selected_name=$(cat $file | awk '{$1=$1};1' |\
    dmenu -i -p "Edit ID" -sf "#83a598" | awk -F '|' '{print $1}' | awk '{$1=$1};1')
    selected_name_noid=$(printf $selected_name | awk -F '[(]' '{printf $1}' | awk '{$1=$1};1')
    [ -z "$selected_name" ] && { notify-send "Error: No bookmark selected"; exit 1 ;} ||
    highest_id=$(grep -c "$selected_name_noid" "$file")
    [ $highest_id -gt 1 ] && {
    selected_id=$(awk -v name="$selected_name" -F '[()]' '$0 ~ name && NF>1 {print $2}' "$file")
    new_id=$(grep -oP "$selected_name_noid \(\K\d+" "$file" | grep -v "$selected_id" | dmenu -p "Move to ID")

    confirmation=$(printf "Yes\nNo" |\
	dmenu -i -p "Swap IDs? $selected_name -> $selected_name_noid ($new_id)") 
    [ $confirmation == "Yes" ] &&
	sed -i "s/$selected_name/$selected_name_noid (temp)/; s/$selected_name_noid ($new_id)/$selected_name/; s/$selected_name_noid (temp)/$selected_name_noid ($new_id)/" $file
    notify-send "Success: IDs were edited"
    sort -t '|' -k1,1 -o "$file" "$file";} || 
    notify-send "Error: There's only one instance of this name"
}

delete_bookmark() {
    [ -s "$file" ] || { notify-send "Error: No bookmarks found"; exit 1 ;} &&
    selected_name=$(cat $file | awk -F '|' '{print $1}' | awk '{$1=$1};1' |\
    dmenu -i -p "Delete Bookmark" -sf "#fb4934")
    [ -z "$selected_name" ] && { notify-send "Error: No bookmark selected"; exit 1 ;} ||
    selected_url=$(grep -w "^$selected_name"  "$file" | awk -F '|' '{print $2}' |\
    awk '{$1=$1};1')
    temp_file=$(mktemp)
    grep -v "$selected_name" "$file" > "$temp_file"; mv $temp_file $file
    notify-send "$selected_name deleted successfully" "$selected_url"
}

[ -f "$file" ] || touch "$file"

pgrep -x "firefox" || { notify-send "Error: Firefox not running"; exit 1 ;} &&

case $1 in
    create)
	create_bookmark ;;
    insert)
	insert_bookmark ;;    
    replace)
	replace_bookmark ;;
    delete)
	delete_bookmark ;;
    *)
	action=$(printf "Create Bookmark\nInsert Bookmark\nReplace Bookmark\nEdit IDs\nDelete Bookmark" | dmenu -p 'Manage Bookmarks' -sf '#fe8019')

	case $action in
	    "Create Bookmark")
		create_bookmark ;;
	    "Insert Bookmark")
		insert_bookmark ;;
	    "Replace Bookmark")
		replace_bookmark ;;
	    "Edit ")
		edit_ids ;;
	    "Delete Bookmark")
		delete_bookmark ;;
	esac ;;
esac
