#!/bin/sh
vol=$(pamixer --get-volume)
vol_human=$(pamixer --get-volume-human)

help() {
cat <<EOF
Usage: getvol [option]

Options:

	h Usage help
	u Increase volume
	d Decrease volume
	m Mute
	p Play / Pause
	n Next
	b Previous

EOF
}

case $1 in
	u)
		[ $vol -lt 100 ] && pamixer -i 5
		pkill -RTMIN+2 dwmblocks
		;;
	d)
		[ $vol -gt 0 ] && pamixer -d 5
		pkill -RTMIN+2 dwmblocks
		;;
	m)
		pamixer -t
		pkill -RTMIN+2 dwmblocks
		;;
	p)
		playerctl -p spotify play-pause
		pkill -RTMIN+1 dwmblocks
		;;
	n)
		playerctl -p spotify next
		pkill -RTMIN+1 dwmblocks
		;;
	b)
		playerctl -p spotify previous
		pkill -RTMIN+1 dwmblocks
		;;
	t)
		[ "$vol_human" == "muted" ] && printf "v:M" || {
		[[ $vol -lt 30 ]] && printf "\x01v:$vol" || {
		[[ $vol -lt 65 ]] && printf "\x01v:$vol" || printf "\x01v:$vol" ;} ;}
		;;
	*)
		help
		;;
esac


case "$BLOCK_BUTTON" in
    1) xdo activate -N Spotify ;;
esac

