#!/bin/sh

choices="Quit dwm\nRefresh dwm\nReboot\nPower off"

chosen=$(echo -e "$choices" | dmenu -p "Menu" -i)

case "$chosen" in
	"Quit dwm")
		killall xinit
		;;
	"Refresh dwm")
		killall dwm
		;;
	"Reboot")
		doas /usr/bin/reboot
		;;
	"Power off")
		doas /usr/bin/poweroff
esac

