#!/bin/bash
interface=org.mpris.MediaPlayer2.Player

dbus-monitor --profile "type='signal',interface='$interface'" |
while read -r line; do
    sleep 0.05
    pkill -RTMIN+1 dwmblocks
done

pkill -RTMIN+1 dwmblocks
